version: '3.8'

services:
  resume-analyzer-dev:
    build: .
    container_name: resume-analyzer-dev
    ports:
      # Forward web service port
      - "8000:8000"
    volumes:
      # Mount source code for development
      - .:/app
      # Mount test files folder
      - ./tests/resources:/app/tests/resources
      # Mount results folder
      - ./results:/app/results
      # Mount logs
      - ./logs:/app/logs
    environment:
      # Development settings
      - LM_STUDIO_URL=http://host.docker.internal:1234/v1/chat/completions
      - DEFAULT_MODEL=google/gemma-3-12b
      - LLM_TIMEOUT=120
      - LOG_LEVEL=DEBUG
      - PYTHONPATH=/app
    networks:
      - resume-network
    # Start web service in development mode
    command: ["python", "run.py"]
    restart: unless-stopped

networks:
  resume-network:
    driver: bridge
